name: PHP Composer CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures the full repository is checked out

      - name: Debug - List Files in Root
        run: ls -la

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"  # Change based on your project
          tools: composer

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer dependencies
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --verbose

      - name: Run test suite
        run: composer run-script test || true  # Avoids breaking workflow if tests are missing

      - name: Debug - Show Installed PHP Extensions
        run: php -m

      - name: Debug - Show Installed Packages
        run: composer show
